/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blueCarbonCreditsSol from "./BlueCarbonCredits.sol";
export type { blueCarbonCreditsSol };
export type { ProjectRegistry } from "./ProjectRegistry";
export type { SoulboundToken } from "./SoulboundToken";
